### ISSUE TITLE
How to choose the code and params for evaluation?

### ISSUE THREAD

**Issue by jiaweiguan** [ProteinDesignLab/protpardelle#10]
If I want to evaluate the model now, which branch of the code would be more suitable?

**Comment by Yaoyaolingbro** [comment]
I have the same question! How we should evaluate the protein generative model? It need a benchmark for it.

**Comment by alexechu** [comment]
What would you like to evaluate the model on? We use a few different metrics and benchmarks in the paper to evaluate backbone quality/diversity and sidechain quality.
