### ISSUE TITLE
minimpnn or ProteinMPNN?

### ISSUE THREAD

**Issue by jiaweiguan** [ProteinDesignLab/protpardelle#13]
Hi,  I have a question. In the final step of the first-stage sampling, the model used ProteinMPNN to design sequences. Can it be designed using minimpnn? Is there a significant difference in their effectiveness? Can sequences designed with MiniMPNN be folded into corresponding structures?

**Comment by zhkim216** [comment]
Hi Jiawei,
We recommend using proteinmpnn at the final step, as the self-consistent metrics of sequences designed with minimpnn is lower than proteinmpnn.
