### ISSUE TITLE
How to correctly use Protpardelle to obtain results consistent with the paper?

### ISSUE THREAD

**Issue by jiaweiguan** [ProteinDesignLab/protpardelle#16]
First, I did not modify the default parameter configuration of the model and used the all-atom mode.

When running the code of "main"， I found that in the first and second stages of sampling, the protein backbone is different. 

I found that in the default parameters, ‘cond information’ is not injected in the following two places.
https://github.com/ProteinDesignLab/protpardelle/blob/7d42fc99d57fe46c7cb55282d1c1e9880bb43aa0/models.py#L1033
https://github.com/ProteinDesignLab/protpardelle/blob/7d42fc99d57fe46c7cb55282d1c1e9880bb43aa0/models.py#L141

**Comment by zhkim216** [comment]
Sorry for replying late. the problem was solved. Please check the new codes.
